version: '3.0'

services:
  db:
    image: postgres:12-alpine
    ports:
      - '6001:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
